//Pizza
export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST'
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS'
export const GET_PIZZAS_FAILED = 'GET_PIZZAS_FAILED'

//Registration, Login
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"
