//PIZZA
export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST'
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS'
export const GET_PIZZAS_FAILED = 'GET_PIZZAS_FAILED'
export const ADD_PIZZA_REQUEST='ADD_PIZZA_REQUEST';
export const ADD_PIZZAS_SUCCESS='ADD_PIZZAS_SUCCESS';
export const ADD_PIZZAS_FAILED='ADD_PIZZAS_FAILED';
export const GET_PIZZABYID_REQUEST='GET_PIZZABYID_REQUEST';
export const GET_PIZZABYID_SUCCESS='GET_PIZZABYID_SUCCESS';
export const GET_PIZZABYID_FAILED='GET_PIZZABYID_FAILED';
export const EDIT_PIZZA_REQUEST='EDIT_PIZZA_REQUEST';
export const EDIT_PIZZA_SUCCESS='EDIT_PIZZA_SUCCESS';
export const EDIT_PIZZA_FAILED='EDIT_PIZZA_FAILED';
export const DELETE_PIZZA_REQUEST='DELETE_PIZZA_REQUEST';
export const DELETE_PIZZA_SUCCESS='DELETE_PIZZA_SUCCESS';
export const DELETE_PIZZA_FAILED='DELETE_PIZZA_FAILED';

//USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED';
export const UPDATE_USER_INFO='UPDATE_USER_INFO';
export const ADD_TO_CART='ADD_TO_CAR';
export const DELETE_FROM_CART='DELETE_FROM_CART';
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS ='GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED ='GET_ALL_USERS_FAILED';
export const DELETE_USER_REQUEST ='DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS ='DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

//ORDER
export const PLACE_ORDER_REQUEST='PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS='PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILED='PLACE_ORDER_FAILED';
export const GET_ORDERS_REQUEST='GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS='GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED='GET_ORDERS_FAILED';
export const GET_ALL_ORDERS_REQUEST='GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS='GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILED='GET_ALL_ORDERS_FAILED';
